2023-12-17 20:37:00,115 INFO    MainThread:931 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-17 20:37:00,115 INFO    MainThread:931 [wandb_setup.py:_flush():76] Configure stats pid to 931
2023-12-17 20:37:00,115 INFO    MainThread:931 [wandb_setup.py:_flush():76] Loading settings from /home/re6101029/.config/wandb/settings
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_setup.py:_flush():76] Loading settings from /home/re6101029/CVPR2023comp/yolov6/wandb/settings
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'tools/train.py', 'program_abspath': '/home/re6101029/CVPR2023comp/yolov6/tools/train.py', 'program': 'tools/train.py'}
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_init.py:_log_setup():524] Logging user logs to /home/re6101029/CVPR2023comp/yolov6/wandb/run-20231217_203700-r8rex5b4/logs/debug.log
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_init.py:_log_setup():525] Logging internal logs to /home/re6101029/CVPR2023comp/yolov6/wandb/run-20231217_203700-r8rex5b4/logs/debug-internal.log
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_init.py:init():564] calling init triggers
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_init.py:init():614] starting backend
2023-12-17 20:37:00,116 INFO    MainThread:931 [wandb_init.py:init():618] setting up manager
2023-12-17 20:37:00,121 INFO    MainThread:931 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-12-17 20:37:00,122 INFO    MainThread:931 [wandb_init.py:init():624] backend started and connected
2023-12-17 20:37:00,132 INFO    MainThread:931 [wandb_init.py:init():716] updated telemetry
2023-12-17 20:37:00,133 INFO    MainThread:931 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-17 20:37:00,590 ERROR   MainThread:931 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-12-17 20:37:00,899 ERROR   MainThread:931 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/re6101029/miniconda3/envs/CVPR/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/re6101029/miniconda3/envs/CVPR/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2023-12-17 20:37:01,903 WARNING MsgRouterThr:931 [router.py:message_loop():77] message_loop has been closed
